<template>
  <section v-if="kind === 'opening'" class="opening" :style="cover"><div><small>{{ label }}</small><b>{{ monogram }}</b><h1>{{ groom }} <i>&amp;</i> {{ bride }}</h1><time>{{ date }}</time><button @click="$emit('open')">MỞ THIỆP</button></div></section>
  <section v-else-if="kind === 'hero'" class="hero" :style="cover"><div><small>{{ label }}</small><h1>{{ groom }} <i>&amp;</i> {{ bride }}</h1><time>{{ date }}</time></div></section>
  <section v-else-if="kind === 'couple'" class="section"><Title number="01" title="Chúng mình"/><div class="couple"><article v-for="p in people" :key="p.role"><img v-if="p.image" :src="p.image" :alt="p.name"><div v-else class="portrait">{{ p.name[0] }}</div><small>{{ p.role }}</small><h3>{{ p.name }}</h3><p>{{ p.text }}</p></article></div></section>
  <section v-else-if="kind === 'story' && story" class="section soft"><Title number="02" :title="wedding.story?.Title || wedding.story?.title || 'Câu chuyện của chúng mình'"/><p>{{ story }}</p></section>
  <section v-else-if="kind === 'events' && events.length" class="section"><Title number="03" title="Thời gian & địa điểm"/><article v-for="e in events" :key="e.Id || e.id" class="event"><time>{{ e.EventTime || e.Time || e.time }}</time><div><h3>{{ e.Title || e.title }}</h3><p>{{ e.EventDate || e.date || e.Day }} {{ e.Month || '' }} {{ e.Year || '' }}</p><p>{{ e.Location || e.location }}<br>{{ e.Address || e.address }}</p><a v-if="e.Map || e.map" :href="e.Map || e.map" target="_blank">Chỉ đường</a></div></article></section>
  <section v-else-if="kind === 'countdown' && target" class="section soft countdown"><Title number="04" title="Đếm ngược đến ngày vui"/><div><b>{{ remain.days }}</b><span>NGÀY</span><b>{{ remain.hours }}</b><span>GIỜ</span><b>{{ remain.minutes }}</b><span>PHÚT</span></div></section>
  <section v-else-if="kind === 'timeline' && timeline.length" class="section"><Title number="05" title="Lịch trình ngày cưới"/><ol><li v-for="x in timeline" :key="x.Id || x.id"><b>{{ x.Time || x.time }}</b><div><h3>{{ x.Title || x.title }}</h3><p>{{ x.Description || x.description }}</p></div></li></ol></section>
  <section v-else-if="kind === 'gallery' && gallery.length" class="section soft"><Title number="06" title="Khoảnh khắc yêu thương"/><div class="gallery"><img v-for="(x,i) in gallery" :key="x.Id || x.id || i" :src="x.Image || x.image || x.url || x" :alt="`Ảnh cưới ${i+1}`"></div></section>
  <section v-else-if="kind === 'map' && events.length" class="section map"><Title number="07" title="Bản đồ tham dự"/><a v-for="e in events.filter(x=>x.Map||x.map)" :key="e.Id || e.id" :href="e.Map || e.map" target="_blank">{{ e.Title || e.title }} — {{ e.Address || e.address }}</a></section>
  <section v-else-if="kind === 'gifts' && gifts.length" class="section soft"><Title number="08" title="Hộp quà mừng cưới"/><article v-for="x in gifts" :key="x.Id || x.id" class="gift"><img v-if="x.QrCode || x.qrCode" :src="x.QrCode || x.qrCode"><div><h3>{{ x.BankName || x.bankName || x.Name || x.name }}</h3><p>{{ x.AccountName || x.accountName }}</p><b>{{ x.AccountNumber || x.accountNumber }}</b></div></article></section>
  <section v-else-if="kind === 'wishes'" class="section"><Title number="09" title="Lời chúc"/><article v-for="x in wishes" :key="x.Id || x.id" class="wish">“{{ x.Message || x.message }}”<b>— {{ x.Name || x.name }}</b></article><p v-if="!wishes.length">Hãy là người đầu tiên gửi lời chúc cho chúng mình.</p></section>
  <footer v-else-if="kind === 'footer'"><b>{{ monogram }}</b><p>{{ wedding.footer?.Message || wedding.footer?.message || 'Sự hiện diện của bạn là niềm vui của chúng mình.' }}</p><strong>{{ groom }} &amp; {{ bride }}</strong></footer>
</template>
<script setup>
import {computed,onBeforeUnmount,onMounted,ref} from 'vue'; import dayjs from 'dayjs';
const props=defineProps({kind:String,wedding:{type:Object,required:true},label:{type:String,default:'THE WEDDING DAY'}}); defineEmits(['open']); const read=(o,...k)=>k.map(x=>o?.[x]).find(x=>x!==undefined&&x!==null&&x!==''); const groom=computed(()=>read(props.wedding,'GroomName','groomName')||read(props.wedding?.couple?.Groom||props.wedding?.couple?.groom,'Name','name')||'Chú rể'),bride=computed(()=>read(props.wedding,'BrideName','brideName')||read(props.wedding?.couple?.Bride||props.wedding?.couple?.bride,'Name','name')||'Cô dâu'),monogram=computed(()=>`${groom.value[0]}&${bride.value[0]}`.toUpperCase()); const raw=computed(()=>read(props.wedding?.hero,'WeddingDate','weddingDate')||read(props.wedding,'WeddingDate','weddingDate')),date=computed(()=>{let d=dayjs(raw.value);return d.isValid()?d.format('DD · MM · YYYY'):''}),cover=computed(()=>{let x=read(props.wedding,'coverImage','CoverImage')||read(props.wedding?.hero,'Image','image','Background','background');return x?{'--cover':`url("${x}")`}:{}}); const events=computed(()=>Array.isArray(props.wedding.events)?props.wedding.events:[]),timeline=computed(()=>Array.isArray(props.wedding.timeline)?props.wedding.timeline:[]),gallery=computed(()=>Array.isArray(props.wedding.gallery)?props.wedding.gallery:[]),gifts=computed(()=>Array.isArray(props.wedding.gifts)?props.wedding.gifts:[]),story=computed(()=>read(props.wedding.story,'Description','description','Content','content')||''),wishes=computed(()=>{let x=props.wedding.guestBook||props.wedding.GuestBook;return Array.isArray(x)?x:x?.Guest||x?.guest||x?.wishes||[]}); const people=computed(()=>{let a=props.wedding.couple?.Groom||props.wedding.couple?.groom||{},b=props.wedding.couple?.Bride||props.wedding.couple?.bride||{};return [{role:'Chú rể',name:groom.value,image:read(a,'Avatar','avatar'),text:read(a,'Description','description')},{role:'Cô dâu',name:bride.value,image:read(b,'Avatar','avatar'),text:read(b,'Description','description')}]}),target=computed(()=>read(props.wedding.countdown,'Target','target')||raw.value),now=ref(Date.now()),timer=setInterval(()=>now.value=Date.now(),1000),remain=computed(()=>{let t=Math.max(0,dayjs(target.value).valueOf()-now.value),m=Math.floor(t/60000);return{days:Math.floor(m/1440),hours:Math.floor(m%1440/60),minutes:m%60}});onBeforeUnmount(()=>clearInterval(timer)); const Title={props:['number','title'],template:'<header><small>{{number}}</small><h2>{{title}}</h2></header>'};
</script>
<style scoped>
.opening,.hero{background:linear-gradient(#0007,#0009),var(--cover) center/cover}.opening{position:fixed;z-index:10;inset:0;display:grid;place-items:center;text-align:center;color:#fff}.opening>div{padding:30px}.opening small,.hero small{letter-spacing:.25em;font:10px Arial}.opening>b,footer>b{display:inline-grid;place-items:center;width:80px;height:80px;margin:20px;border:1px solid currentColor;border-radius:50%;font-size:20px}.opening h1,.hero h1{font:400 clamp(40px,8vw,72px) Georgia}.opening i,.hero i{color:var(--accent)}button,a{display:inline-block;padding:12px 18px;margin-top:18px;background:var(--primary);border:1px solid var(--accent);color:#fff;text-decoration:none}.hero{min-height:620px;display:grid;place-items:center;text-align:center;color:#fff}.section{padding:65px clamp(22px,7vw,70px)}.soft{background:#00000008}header{display:flex;gap:14px;align-items:center;margin-bottom:28px}header small,.couple small{color:var(--accent);letter-spacing:.14em}h2{margin:0;font:400 clamp(30px,4vw,44px) Georgia}h3{font:400 23px Georgia}p{line-height:1.8;color:var(--muted)}.couple{display:grid;grid-template-columns:1fr 1fr;gap:25px;text-align:center}.couple img,.portrait{width:100%;aspect-ratio:4/5;object-fit:cover;background:var(--primary);color:white;display:grid;place-items:center;font-size:40px}.couple small{display:block;margin-top:15px}.event,.gift{display:flex;gap:24px;padding:23px 0;border-top:1px solid #0002}.event>time{min-width:70px;color:var(--accent);font-size:22px}.event p{margin:7px 0}ol{padding:0;list-style:none}li{display:grid;grid-template-columns:90px 1fr;gap:18px;border-left:1px solid var(--accent);padding:15px 22px}li>b{color:var(--accent)}li h3,li p{margin:0}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.gallery img{width:100%;height:220px;object-fit:cover}.gift{align-items:center}.gift img{width:110px;height:110px;object-fit:contain}.wish{margin:15px 0;padding:20px;border-left:3px solid var(--accent);background:#fff8}.wish b{display:block;margin-top:10px}.countdown>div{display:flex;gap:12px;align-items:baseline;justify-content:center}.countdown b{font-size:40px;color:var(--accent)}.countdown span{font-size:10px}.map a{display:block;margin:12px 0}footer{padding:65px 30px;text-align:center;background:var(--primary);color:#fff}footer p{max-width:520px;margin:15px auto;color:#fffc}@media(max-width:600px){.section{padding:48px 22px}.gallery{grid-template-columns:1fr 1fr}.gallery img{height:170px}li{grid-template-columns:65px 1fr;padding:14px}.event{gap:14px}}
</style>
