<template>
  <div class="invite" :class="theme.id" :style="vars">
    <section v-if="!opened" class="cover" :style="coverStyle"><div><p>{{ theme.kicker }}</p><b>{{ monogram }}</b><h1>{{ groomName }} <i>&amp;</i> {{ brideName }}</h1><time>{{ dateLabel }}</time><button @click="open">MỞ THIỆP</button></div></section>
    <main v-else>
      <section class="hero" :style="coverStyle"><div><p>{{ theme.kicker }}</p><h1>{{ groomName }} <i>&amp;</i> {{ brideName }}</h1><time>{{ dateLabel }}</time></div></section>
      <section v-if="on('Couple')" class="section"><header><small>01</small><h2>Chúng mình</h2></header><div class="couple"><article v-for="person in people" :key="person.role"><img v-if="person.image" :src="person.image" :alt="person.name"><div v-else class="portrait">{{ person.name[0] }}</div><small>{{ person.role }}</small><h3>{{ person.name }}</h3><p>{{ person.description }}</p></article></div></section>
      <section v-if="on('Story') && story" class="section soft"><header><small>02</small><h2>{{ wedding.story?.Title || wedding.story?.title || 'Câu chuyện của chúng mình' }}</h2></header><p>{{ story }}</p></section>
      <section v-if="on('Events') && events.length" class="section"><header><small>03</small><h2>Thời gian & địa điểm</h2></header><article v-for="event in events" :key="event.Id || event.id" class="event"><time>{{ event.EventTime || event.Time || event.time }}</time><div><h3>{{ event.Title || event.title }}</h3><p>{{ event.EventDate || event.date || event.Day }} {{ event.Month || '' }} {{ event.Year || '' }}</p><p>{{ event.Location || event.location }}<br>{{ event.Address || event.address }}</p><a v-if="event.Map || event.map" :href="event.Map || event.map" target="_blank" rel="noopener">Chỉ đường</a></div></article></section>
      <section v-if="on('Timeline') && timeline.length" class="section soft"><header><small>04</small><h2>Lịch trình</h2></header><ol><li v-for="item in timeline" :key="item.Id || item.id"><b>{{ item.Time || item.time }}</b><div><h3>{{ item.Title || item.title }}</h3><p>{{ item.Description || item.description }}</p></div></li></ol></section>
      <section v-if="on('Gallery') && gallery.length" class="section"><header><small>05</small><h2>Khoảnh khắc yêu thương</h2></header><div class="gallery"><img v-for="(photo, i) in gallery" :key="photo.Id || photo.id || i" :src="photo.Image || photo.image || photo.url || photo" :alt="`Ảnh cưới ${i + 1}`"></div></section>
      <section v-if="on('Gift') && gifts.length" class="section soft"><header><small>06</small><h2>Hộp quà mừng cưới</h2></header><article v-for="gift in gifts" :key="gift.Id || gift.id" class="gift"><img v-if="gift.QrCode || gift.qrCode" :src="gift.QrCode || gift.qrCode" alt="Mã QR"><div><h3>{{ gift.BankName || gift.bankName || gift.Name || gift.name }}</h3><p>{{ gift.AccountName || gift.accountName }}</p><b>{{ gift.AccountNumber || gift.accountNumber }}</b></div></article></section>
      <section v-if="on('GuestBook')" class="section"><header><small>07</small><h2>Lời chúc</h2></header><article v-for="wish in wishes" :key="wish.Id || wish.id" class="wish">“{{ wish.Message || wish.message }}”<b>— {{ wish.Name || wish.name }}</b></article><p v-if="!wishes.length">Hãy là người đầu tiên gửi lời chúc cho chúng mình.</p></section>
      <footer v-if="on('Footer')"><b>{{ monogram }}</b><p>{{ wedding.footer?.Message || wedding.footer?.message || 'Sự hiện diện của bạn là niềm vui của chúng mình.' }}</p><strong>{{ groomName }} &amp; {{ brideName }}</strong></footer>
    </main><FloatingMusic v-if="music.Enabled" ref="musicRef" :music="music" />
  </div>
</template>
<script setup>
import { computed, nextTick, ref } from 'vue'; import dayjs from 'dayjs'; import FloatingMusic from '@/components/common/FloatingMusic.vue';
const props=defineProps({wedding:{type:Object,required:true},theme:{type:Object,required:true}}); const opened=ref(false),musicRef=ref(null); const get=(o,...keys)=>keys.map(k=>o?.[k]).find(v=>v!==undefined&&v!==null&&v!==''); const groom=computed(()=>props.wedding?.couple?.Groom||props.wedding?.couple?.groom||{}),bride=computed(()=>props.wedding?.couple?.Bride||props.wedding?.couple?.bride||{}); const groomName=computed(()=>get(props.wedding,'GroomName','groomName')||get(groom.value,'Name','name')||'Chú rể'),brideName=computed(()=>get(props.wedding,'BrideName','brideName')||get(bride.value,'Name','name')||'Cô dâu'); const monogram=computed(()=>`${groomName.value[0]}&${brideName.value[0]}`.toUpperCase()); const rawDate=computed(()=>get(props.wedding?.hero,'WeddingDate','weddingDate')||get(props.wedding,'WeddingDate','weddingDate')); const dateLabel=computed(()=>{const d=dayjs(rawDate.value);return d.isValid()?d.format('DD · MM · YYYY'):''}); const image=computed(()=>get(props.wedding,'coverImage','CoverImage')||get(props.wedding?.hero,'Image','image','Background','background')||''); const coverStyle=computed(()=>image.value?{'--cover':`url("${image.value}")`}:{}); const vars=computed(()=>({'--primary':props.theme.primary,'--accent':props.theme.accent,'--paper':props.theme.paper,'--ink':props.theme.ink,'--muted':props.theme.muted})); const events=computed(()=>Array.isArray(props.wedding?.events)?props.wedding.events:[]),timeline=computed(()=>Array.isArray(props.wedding?.timeline)?props.wedding.timeline:[]),gallery=computed(()=>Array.isArray(props.wedding?.gallery)?props.wedding.gallery:[]),gifts=computed(()=>Array.isArray(props.wedding?.gifts)?props.wedding.gifts:[]); const story=computed(()=>get(props.wedding?.story,'Description','description','Content','content')||''); const wishes=computed(()=>{const b=props.wedding?.guestBook||props.wedding?.GuestBook;return Array.isArray(b)?b:b?.Guest||b?.guest||b?.wishes||[]}); const people=computed(()=>[{role:'Chú rể',name:groomName.value,image:get(groom.value,'Avatar','avatar','Image','image'),description:get(groom.value,'Description','description')},{role:'Cô dâu',name:brideName.value,image:get(bride.value,'Avatar','avatar','Image','image'),description:get(bride.value,'Description','description')}]); const music=computed(()=>{const m=props.wedding?.music||{};return {Enabled:m.Enabled??m.enabled??false,Url:m.Url||m.url||'',Title:m.Title||m.title||''}}); function on(name){const s=props.wedding?.settings||props.wedding?.Settings||{};return (s[`Show${name}`]??s[`show${name}`])!==false} async function open(){opened.value=true;await nextTick();musicRef.value?.play?.()}
</script>
<style scoped>
.invite{min-height:100vh;background:var(--paper);color:var(--ink);font-family:Georgia,serif}.cover,.hero{background:linear-gradient(#0007,#0009),var(--cover) center/cover}.cover{position:fixed;z-index:10;inset:0;display:grid;place-items:center;color:#fff;text-align:center}.cover>div{padding:35px}.cover p,.hero p{letter-spacing:.25em;text-transform:uppercase;font:10px Arial}.cover b,footer>b{display:inline-grid;place-items:center;width:80px;height:80px;border:1px solid currentColor;border-radius:50%;font-size:20px}.cover h1,.hero h1{font-size:clamp(40px,8vw,72px);font-weight:400}.cover i,.hero i{color:var(--accent)}button,a{display:inline-block;margin-top:22px;padding:13px 20px;border:1px solid var(--accent);background:var(--primary);color:#fff;text-decoration:none}.hero{min-height:620px;display:grid;place-items:center;color:#fff;text-align:center}.hero>div{padding:30px}.section{padding:70px clamp(22px,7vw,70px)}.soft{background:#00000008}header{display:flex;gap:14px;align-items:center;margin-bottom:30px}header small,.couple small{color:var(--accent);letter-spacing:.14em;text-transform:uppercase}h2{margin:0;font-size:clamp(30px,4vw,44px);font-weight:400}h3{font-size:23px;font-weight:400}p{line-height:1.8;color:var(--muted)}.couple{display:grid;grid-template-columns:1fr 1fr;gap:25px;text-align:center}.couple img,.portrait{width:100%;aspect-ratio:4/5;object-fit:cover;background:var(--primary);color:#fff;display:grid;place-items:center;font-size:40px}.couple small{display:block;margin-top:16px}.event,.gift{display:flex;gap:24px;padding:25px 0;border-top:1px solid #0002}.event>time{min-width:70px;color:var(--accent);font-size:23px}.event p{margin:7px 0}.event a{margin-top:5px;padding:8px 13px;font-size:13px}.timeline ol{padding:0;list-style:none}.timeline li{display:grid;grid-template-columns:90px 1fr;gap:18px;border-left:1px solid var(--accent);padding:15px 22px}.timeline b{color:var(--accent)}.timeline h3,.timeline p{margin:0}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.gallery img{width:100%;height:220px;object-fit:cover}.gallery img:nth-child(3n+1){height:450px;grid-row:span 2}.gift{align-items:center}.gift img{width:110px;height:110px;object-fit:contain}.wish{margin:15px 0;padding:20px;border-left:3px solid var(--accent);background:#fff8}.wish b{display:block;margin-top:10px}footer{padding:70px 30px;background:var(--primary);color:#fff;text-align:center}footer p{max-width:520px;margin:20px auto;color:#fffc}@media(max-width:600px){.section{padding:50px 22px}.gallery{grid-template-columns:1fr 1fr}.gallery img,.gallery img:nth-child(3n+1){height:170px;grid-row:auto}.timeline li{grid-template-columns:65px 1fr;padding:14px}.event{gap:14px}}
</style>
